rootProject.name = "CloudTVStream"

include("Filmmirasim")
include("TVJustin")
include("NetFilim")
include("NetDiziHD")
include("KorkuTV")
include("FilmDozu")
include("KultFilmler")
include("SinePort")
include("FilmZal")
include("NadirFilm")
include("HDFilmizleTo")
include("CanliTV")
include("DaddyLive")
